### ISSUE TITLE
Aggregate RSS feeds

### ISSUE THREAD

**Issue by mhanberg** [mhanberg/planet#7]
## Tasks
- [x] Gather feeds from urls
- [x] combine into a new RSS feed

## AC
- [x] Posts are shown in descending order by date at "/"
    - displays:
        - [x] post title
        - [x] author
        - [x] published date
        - [x] post
        - [x] url
- [x] Style according to mockup
- [x] Aggregated feed is served at "/feed.xml"
